import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'BigPlant',
      'copyright': 'Copyright 2026 © BigPlant',
      'login_page': 'Login',
      'register_page': 'Register',
      'forgot_password_page': 'Forgot Password',
      'verify_email': 'Verify Email',
      'create_new_pass': 'Create New Password',
      'enter_new_pass': 'Enter your new password.',
      'login': 'Login',
      'register': 'Register',
      'next': 'Next',
      'got_it': 'Got it',
      'forgot_password': 'Forgot password?',
      'dont_have_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'username_hint': 'Enter your username or email',
      'register_username_hint': 'Enter your username',
      'password_hint': 'Enter your password',
      'email_hint': 'Enter your email',
      'phone_hint': 'Enter your phone number',
      're_password_hint': 'Re-enter your password',
      'verify_desc': 'Enter the 4-digit code sent to your email.',
      'reset_desc': 'Enter your email to receive a password reset OTP.',
      'verification_success': 'Success!',
      'verification_success_detail': 'Your email has been verified.',
      'resetpassword_success':
          'Your password has been updated. You can now log in.',
      'didnt_get_email': "Didn't receive the code?",
      'resend': 'Resend code',
      'language': 'Language',
      'toggle_language': 'VI / EN',
      'login_with_google': 'Login with Google',
      'google_coming_soon': 'Google login is not migrated yet',
      'terms': 'I agree to the terms and policies',
      'register_terms':
          'I agree to the terms of use and privacy policy.',
      'error_username_empty': "Username can't be empty.",
      'error_password_empty': "Password can't be empty.",
      'error_password_invalid':
          'Password must contain at least 8 characters.',
      'error_email_empty': "Email can't be empty.",
      'error_email_invalid': 'Email format is invalid.',
      'error_repassword_empty': "Password confirmation can't be empty.",
      'error_repassword_invalid': "Passwords don't match.",
      'error_otp_invalid': 'The OTP is invalid or expired.',
      'error_checkbox': 'You must agree to the terms and privacy policy.',
      'session_title': 'Authenticated Session',
      'session_desc': 'You are signed in.',
      'logout': 'Log out',
      'toast_saved_clipboard': 'Saved to clipboard',
      'toast_success_default': 'Success',
      'home_tab': 'Home',
      'scan_tab': 'Scan',
      'cart_tab': 'Cart',
      'settings_tab': 'Settings',
      'home_title': 'Discover Greenery',
      'home_subtitle': 'Pick healthy plants for your space',
      'home_search_hint': 'Search plants, pots or accessories',
      'popular_plants': 'Popular this week',
      'category_indoor': 'Indoor',
      'category_outdoor': 'Outdoor',
      'category_pot': 'Pots',
      'category_air': 'Air purifier',
      'cart_title': 'Your Cart',
      'checkout_now': 'Checkout now',
      'settings_title': 'Settings',
      'notify_deals': 'Deal notifications',
      'notify_tips': 'Plant care tips',
      'scan_placeholder_title': 'Scan module is coming next',
      'scan_placeholder_desc':
          'Camera and photo upload flow will be implemented next.',
      'scan_title': 'Plant Scanner',
      'scan_subtitle': 'Capture or upload a plant photo for instant analysis',
      'scan_empty_state': 'Your selected image will appear here',
      'scan_camera': 'Take photo',
      'scan_gallery': 'Upload photo',
      'scan_tips_title': 'Tips for better scan quality',
      'scan_tip_1': 'Use bright natural light and avoid blur.',
      'scan_tip_2': 'Keep one main plant object in frame.',
      'scan_tip_3': 'Capture leaves and stem clearly for better matching.',
      'scan_result_title': 'Scan Result',
      'plant_identity': 'Plant identity',
      'field_common_name': 'Common name',
      'field_scientific_name': 'Scientific name',
      'field_family': 'Family',
      'field_order': 'Order',
      'field_genus': 'Genus',
      'field_species': 'Species',
      'field_description': 'Description',
      'field_uses': 'Uses',
      'field_advantages': 'Advantages',
      'field_note': 'Note (raw response)',
      'distribution_map': 'Distribution map',
      'distribution_not_available': 'No geolocation distribution provided yet.',
      'distribution_view_details': 'View details',
      'distribution_detail_title': 'Distribution locations',
      'distribution_location': 'Location',
      'confidence': 'Confidence',
      'confidence_unknown': 'Confidence: Unknown',
      'scan_camera_realtime_title': 'Realtime Camera Scan',
      'scan_camera_init_failed': 'Unable to initialize camera.',
      'scan_local_mode_badge': 'Local ONNX realtime mode',
      'scan_realtime_waiting': 'Point camera to a plant...',
      'scan_open_result': 'Open result details',
      'scan_fast_analysis': 'Fast analysis',
      'scan_topk_badge': 'Top-5 detection',
      'scan_natural_light_badge': 'Best in natural light',
      'scan_preview_title': 'Start with a clear plant photo',
      'scan_preview_subtitle':
          'Center one main plant subject for the most reliable result.',
      'scan_latest_capture': 'Latest capture ready',
      'scan_scanning_progress_title': 'Analyzing your plant',
      'scan_scanning_progress_body':
          'Reviewing image features, taxonomy signals, and top matches.',
      'scan_live_analysis': 'Live analysis',
      'scan_local_model': 'Local model',
      'scan_center_guide': 'Align leaves inside the guide',
      'scan_target_hint': 'Keep the leaf edges sharp and well lit.',
      'scan_prediction_ready': 'Prediction ready for review',
      'scan_framework_badge': 'Inference',
      'scan_result_overview': 'Result overview',
      'scan_reference_snapshot': 'Reference snapshot',
      'plant_profile': 'Plant profile',
      'care_requirements': 'Care & safety',
      'field_aliases': 'Aliases',
      'field_habitat': 'Habitat',
      'field_morphology': 'Morphology',
      'field_characteristics': 'Characteristics',
      'field_light': 'Light',
      'field_water': 'Water',
      'field_soil': 'Soil',
      'field_toxicity': 'Toxicity',
      'field_growth_habit': 'Growth habit',
      'field_seasonality': 'Seasonality',
      'field_source_quality': 'Source quality',
      'distribution_points': 'Mapped points',
      'distribution_regions': 'Named regions',
      'distribution_view_map': 'Open map view',
      'distribution_layers': 'Layers',
      'distribution_filter': 'Filter',
      'distribution_recenter': 'Recenter',
      'distribution_locate': 'Locate',
      'distribution_sheet_summary': 'Coverage summary',
      'auth_login_title': 'Welcome back',
      'auth_login_subtitle':
          'Log in to continue your journey through the plant world.',
      'auth_username_label': 'Username or Email',
      'auth_password_label': 'Password',
      'auth_or': 'or',
      'auth_register_link': 'Register now',
      'auth_register_title': 'Create a new account',
      'auth_register_subtitle':
          'Start exploring plants with BigPlant.',
      'auth_phone_optional': 'optional',
      'auth_phone_label': 'Phone number',
      'auth_confirm_password_label': 'Confirm Password',
      'auth_return_login': 'Back to Login',
      'auth_forgot_desc': 'Enter your email to receive a password reset OTP.',
      'auth_continue': 'Continue',
      'auth_register_otp_desc':
          'We sent a 4-digit OTP code to your email',
      'auth_forgot_otp_title': 'Verify Reset Password',
      'auth_forgot_otp_desc':
          'Please enter the 4-digit code sent to your email',
      'auth_resend_timer': 'Resend code (00:45)',
      'auth_new_password_title': 'Create a new password',
      'auth_new_password_desc':
          'Enter and confirm your new password to keep your account secure.',
      'auth_new_password_label': 'New password',
      'auth_new_password_hint': 'Enter new password',
      'auth_confirm_new_password_label': 'Confirm new password',
      'auth_confirm_new_password_hint': 'Re-enter new password',
      'auth_password_rule': 'At least 8 characters, including letters and numbers.',
      'auth_save_password': 'Save password',
      'auth_success_title': 'Success!',
      'auth_back_to_login': 'Back to Login',
      'auth_loading': 'Loading...',
    },
    'vi': {
      'app_name': 'BigPlant',
      'copyright': 'Bản quyền 2026 © BigPlant',
      'login_page': 'Đăng nhập',
      'register_page': 'Đăng ký',
      'forgot_password_page': 'Quên mật khẩu',
      'verify_email': 'Xác thực Email',
      'create_new_pass': 'Tạo mật khẩu mới',
      'enter_new_pass': 'Nhập mật khẩu mới của bạn.',
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'next': 'Tiếp tục',
      'got_it': 'Hoàn thành',
      'forgot_password': 'Quên mật khẩu?',
      'dont_have_account': 'Chưa có tài khoản?',
      'have_account': 'Đã có tài khoản?',
      'username_hint': 'Nhập email của bạn',
      'register_username_hint': 'Nhập tên người dùng',
      'password_hint': 'Nhập mật khẩu',
      'email_hint': 'Nhập địa chỉ email',
      'phone_hint': 'Nhập số điện thoại',
      're_password_hint': 'Nhập lại mật khẩu',
      'verify_desc': 'Nhập mã 4 chữ số đã được gửi đến email.',
      'reset_desc': 'Nhập email để nhận mã OTP khôi phục mật khẩu.',
      'verification_success': 'Thành công!',
      'verification_success_detail':
          'Email của bạn đã được xác thực thành công.',
      'resetpassword_success':
          'Mật khẩu của bạn đã được cập nhật thành công. Bây giờ bạn có thể đăng nhập.',
      'didnt_get_email': 'Chưa nhận được mã?',
      'resend': 'Gửi lại mã',
      'language': 'Ngôn ngữ',
      'toggle_language': 'VI / EN',
      'login_with_google': 'Đăng nhập với Google',
      'google_coming_soon': 'Đăng nhập Google chưa được chuyển logic',
      'terms': 'Tôi đồng ý với điều khoản & chính sách',
      'register_terms':
          'Đồng ý với điều khoản sử dụng và chính sách bảo mật của chúng tôi.',
      'error_username_empty': 'Tên đăng nhập không được để trống.',
      'error_password_empty': 'Mật khẩu không được để trống.',
      'error_password_invalid': 'Mật khẩu phải dài ít nhất 8 ký tự.',
      'error_email_empty': 'Email không được để trống.',
      'error_email_invalid': 'Email sai định dạng. Vui lòng kiểm tra lại.',
      'error_repassword_empty': 'Xác nhận mật khẩu không được để trống.',
      'error_repassword_invalid': 'Mật khẩu không khớp.',
      'error_otp_invalid': 'Mã OTP không hợp lệ hoặc đã hết hạn.',
      'error_checkbox': 'Bạn phải đồng ý với điều khoản và chính sách bảo mật.',
      'session_title': 'Phiên xác thực',
      'session_desc': 'Bạn đã đăng nhập.',
      'logout': 'Đăng xuất',
      'toast_saved_clipboard': 'Đã lưu vào bộ nhớ tạm',
      'toast_success_default': 'Thành công',
      'home_tab': 'Trang chủ',
      'scan_tab': 'Quét',
      'cart_tab': 'Giỏ hàng',
      'settings_tab': 'Cài đặt',
      'home_title': 'Khám phá cây xanh',
      'home_subtitle': 'Chọn cây khỏe đẹp cho không gian của bạn',
      'home_search_hint': 'Tìm cây, chậu hoặc phụ kiện',
      'popular_plants': 'Sản phẩm nổi bật tuần này',
      'category_indoor': 'Trong nhà',
      'category_outdoor': 'Ngoài trời',
      'category_pot': 'Chậu cây',
      'category_air': 'Lọc không khí',
      'cart_title': 'Giỏ hàng của bạn',
      'checkout_now': 'Thanh toán ngay',
      'settings_title': 'Cài đặt',
      'notify_deals': 'Thông báo khuyến mãi',
      'notify_tips': 'Mẹo chăm sóc cây',
      'scan_placeholder_title': 'Chức năng quét sẽ triển khai tiếp theo',
      'scan_placeholder_desc':
          'Luồng camera và tải ảnh sẽ được triển khai ở bước tiếp theo.',
      'scan_title': 'Quét cây',
      'scan_subtitle': 'Chụp hoặc tải ảnh cây để phân tích nhanh',
      'scan_empty_state': 'Ảnh bạn chọn sẽ hiển thị ở đây',
      'scan_camera': 'Chụp ảnh',
      'scan_gallery': 'Tải ảnh lên',
      'scan_tips_title': 'Mẹo để quét chính xác hơn',
      'scan_tip_1': 'Chụp nơi đủ sáng và tránh rung tay.',
      'scan_tip_2': 'Đặt một cây chính vào trung tâm khung hình.',
      'scan_tip_3': 'Hiển thị rõ lá và thân cây để nhận diện tốt hơn.',
      'scan_result_title': 'Kết quả quét',
      'plant_identity': 'Định danh cây',
      'field_common_name': 'Tên thường gọi',
      'field_scientific_name': 'Tên khoa học',
      'field_family': 'Họ',
      'field_order': 'Bộ',
      'field_genus': 'Chi',
      'field_species': 'Loài',
      'field_description': 'Mô tả',
      'field_uses': 'Công dụng',
      'field_advantages': 'Ưu điểm',
      'field_note': 'Ghi chú (raw response)',
      'distribution_map': 'Bản đồ phân bố',
      'distribution_not_available': 'Chưa có dữ liệu tọa độ phân bố.',
      'distribution_view_details': 'Xem chi tiết',
      'distribution_detail_title': 'Danh sách địa điểm phân bố',
      'distribution_location': 'Địa điểm',
      'confidence': 'Độ tin cậy',
      'confidence_unknown': 'Độ tin cậy: Chưa rõ',
      'scan_camera_realtime_title': 'Quét camera thời gian thực',
      'scan_camera_init_failed': 'Không thể khởi tạo camera.',
      'scan_local_mode_badge': 'Chế độ ONNX cục bộ thời gian thực',
      'scan_realtime_waiting': 'Đưa camera vào cây để nhận diện...',
      'scan_open_result': 'Mở chi tiết kết quả',
      'scan_fast_analysis': 'Phân tích nhanh',
      'scan_topk_badge': 'Nhận diện top-5',
      'scan_natural_light_badge': 'Tốt nhất dưới ánh sáng tự nhiên',
      'scan_preview_title': 'Bắt đầu với ảnh cây rõ nét',
      'scan_preview_subtitle':
          'Đặt một cây chính vào trung tâm để cho kết quả ổn định hơn.',
      'scan_latest_capture': 'Ảnh mới đã sẵn sàng',
      'scan_scanning_progress_title': 'Đang phân tích cây của bạn',
      'scan_scanning_progress_body':
          'Đối chiếu đặc điểm hình ảnh, tín hiệu phân loại và các kết quả phù hợp nhất.',
      'scan_live_analysis': 'Phân tích trực tiếp',
      'scan_local_model': 'Mô hình cục bộ',
      'scan_center_guide': 'Căn lá cây vào trong khung dẫn',
      'scan_target_hint': 'Giữ viền lá sắc nét và đủ sáng.',
      'scan_prediction_ready': 'Kết quả đã sẵn sàng để xem',
      'scan_framework_badge': 'Suy luận',
      'scan_result_overview': 'Tóm tắt kết quả',
      'scan_reference_snapshot': 'Thông tin tham chiếu',
      'plant_profile': 'Hồ sơ thực vật',
      'care_requirements': 'Chăm sóc & an toàn',
      'field_aliases': 'Tên khác',
      'field_habitat': 'Môi trường sống',
      'field_morphology': 'Hình thái',
      'field_characteristics': 'Đặc điểm',
      'field_light': 'Ánh sáng',
      'field_water': 'Nước',
      'field_soil': 'Đất',
      'field_toxicity': 'Độc tính',
      'field_growth_habit': 'Dáng sinh trưởng',
      'field_seasonality': 'Mùa vụ',
      'field_source_quality': 'Độ tin cậy nguồn',
      'distribution_points': 'Điểm phân bố',
      'distribution_regions': 'Khu vực phân bố',
      'distribution_view_map': 'Mở bản đồ',
      'distribution_layers': 'Lớp bản đồ',
      'distribution_filter': 'Bộ lọc',
      'distribution_recenter': 'Căn lại tâm',
      'distribution_locate': 'Đi tới điểm',
      'distribution_sheet_summary': 'Tóm tắt phân bố',
      'auth_login_title': 'Chào mừng trở lại',
      'auth_login_subtitle':
          'Đăng nhập để tiếp tục hành trình khám phá thế giới thực vật của bạn.',
      'auth_username_label': 'Username hoặc Email',
      'auth_password_label': 'Mật khẩu',
      'auth_or': 'hoặc',
      'auth_register_link': 'Đăng ký ngay',
      'auth_register_title': 'Tạo tài khoản mới',
      'auth_register_subtitle':
          'Bắt đầu hành trình khám phá thực vật cùng BigPlant.',
      'auth_phone_optional': 'tùy chọn',
      'auth_phone_label': 'Số điện thoại',
      'auth_confirm_password_label': 'Nhập lại Password',
      'auth_return_login': 'Quay lại Đăng nhập',
      'auth_forgot_desc': 'Nhập email của bạn để nhận mã OTP khôi phục mật khẩu.',
      'auth_continue': 'Tiếp tục',
      'auth_register_otp_desc':
          'Chúng tôi đã gửi mã OTP gồm 4 chữ số đến email',
      'auth_forgot_otp_title': 'Xác minh Reset Password',
      'auth_forgot_otp_desc':
          'Vui lòng nhập mã 4 số đã được gửi đến email',
      'auth_resend_timer': 'Gửi lại mã (00:45)',
      'auth_new_password_title': 'Tạo mật khẩu mới',
      'auth_new_password_desc':
          'Vui lòng nhập mật khẩu mới và xác nhận lại để đảm bảo an toàn cho tài khoản của bạn.',
      'auth_new_password_label': 'Mật khẩu mới',
      'auth_new_password_hint': 'Nhập mật khẩu mới',
      'auth_confirm_new_password_label': 'Xác nhận mật khẩu mới',
      'auth_confirm_new_password_hint': 'Nhập lại mật khẩu mới',
      'auth_password_rule': 'Tối thiểu 8 ký tự, bao gồm chữ và số.',
      'auth_save_password': 'Lưu mật khẩu',
      'auth_success_title': 'Thành công!',
      'auth_back_to_login': 'Quay lại Đăng nhập',
      'auth_loading': 'Loading...',
    },
  };

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'vi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
